/**
 * Auto-generated asset identity — single source of truth.
 *
 * Assets created by the layout-import "Build in 3D" wizard embed a signature of
 * the form `[autolayout:<key>]` in their description so they can be (a) reused
 * idempotently on re-runs and (b) grouped/bulk-managed in the asset views.
 */

/** Prefix used inside the bracketed signature, e.g. `[autolayout:10x8x20|front|…]`. */
export const AUTO_ASSET_SIGNATURE_PREFIX = 'autolayout';

/** Matches the bracketed signature anywhere in an asset description. */
export const AUTO_ASSET_SIGNATURE_RE = new RegExp(`\\[(${AUTO_ASSET_SIGNATURE_PREFIX}:[^\\]]+)\\]`);

/** Extract the auto-layout signature from an asset description, if present. */
export function autoAssetSignature(description?: string | null): string | null {
  if (!description) return null;
  const match = description.match(AUTO_ASSET_SIGNATURE_RE);
  return match ? match[1] : null;
}

/** True when an asset was auto-generated by the layout-import wizard. */
export function isAutoGeneratedAsset(asset: { description?: string | null }): boolean {
  return autoAssetSignature(asset.description) !== null;
}
