module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.test.ts', '**/?(*.)+(spec|test).ts'],
  testPathIgnorePatterns: [
    '/node_modules/',
    '/__tests__/mocks/',
    '/__tests__/utils/',
    'detectUnits\\.regression\\.test\\.ts$',
  ],
  transform: {
    '^.+\\.ts$': ['ts-jest', {
      useESM: false,
      tsconfig: 'tsconfig.json',
      diagnostics: false,
    }],
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/*.test.ts',
    '!src/**/*.spec.ts',
    '!src/**/__tests__/**',
    // Gate exclusions — see test:coverage:full for all-src audit
    '!src/database/migrations/**',
    '!src/database/seeds/**',
    '!src/index.ts',
    '!src/models/**',
    '!src/bludesign/**',
    'src/bludesign/layout-import/**/*.ts',
    '!src/bludesign/layout-import/**/__tests__/**',
    '!src/bludesign/layout-import/opencv.ts',
    '!src/bludesign/layout-import/image/**',
    '!src/bludesign/layout-import/detection/detectRectangles.ts',
    '!src/bludesign/layout-import/ocr/cropLabel.ts',
    '!src/bludesign/layout-import/ocr/ocrLabels.ts',
    '!src/bludesign/layout-import/detectUnits.ts',
    '!src/bludesign/layout-import/index.ts',
    '!src/services/database.service.ts',
    '!src/services/migration.service.ts',
    '!src/routes/dev.routes.ts',
    '!src/services/fms/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  setupFiles: ['<rootDir>/src/__tests__/jest-preload-env.cjs'],
  setupFilesAfterEnv: ['<rootDir>/src/__tests__/setup-mocks.ts'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@/config/(.*)$': '<rootDir>/src/config/$1',
    '^@/controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^@/middleware/(.*)$': '<rootDir>/src/middleware/$1',
    '^@/models/(.*)$': '<rootDir>/src/models/$1',
    '^@/routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@/services/(.*)$': '<rootDir>/src/services/$1',
    '^@/utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@/types/(.*)$': '<rootDir>/src/types/$1',
  },
  transformIgnorePatterns: [
    'node_modules/(?!(uuid)/)',
  ],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  testTimeout: 10000,
  maxWorkers: process.env.CI ? 1 : '50%',
};
