/**
 * Auto-generated asset folder — card-sized when collapsed, expands to fit contents.
 *
 * Used in the editor asset browser and the assets catalog page so layout-import
 * units stay grouped without dominating the grid.
 */

import React from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import {
  ChevronDownIcon,
  ChevronRightIcon,
  FolderIcon,
  TrashIcon,
} from '@heroicons/react/24/outline';

export type AutoGeneratedFolderLayout = 'compact' | 'catalog-grid' | 'catalog-list';

export interface AutoGeneratedAssetFolderProps {
  title?: string;
  count: number;
  expanded: boolean;
  onToggle: () => void;
  isDark: boolean;
  layout: AutoGeneratedFolderLayout;
  children: React.ReactNode;
  /** Fixed card width (editor compact layout). */
  cardWidth?: number;
  /** Fixed card height (editor compact layout). */
  cardHeight?: number;
  /** Inner grid column count (editor compact layout). */
  columns?: number;
  /** Inner grid gap in px (editor compact layout). */
  gap?: number;
  /** Tailwind classes for the inner grid (catalog layouts). */
  innerGridClassName?: string;
  onDeleteAll?: () => void;
  deleteTitle?: string;
}

export const AutoGeneratedAssetFolder: React.FC<AutoGeneratedAssetFolderProps> = ({
  title = 'Auto-generated',
  count,
  expanded,
  onToggle,
  isDark,
  layout,
  children,
  cardWidth = 96,
  cardHeight = 108,
  columns = 4,
  gap = 8,
  innerGridClassName,
  onDeleteAll,
  deleteTitle = 'Delete all auto-generated assets',
}) => {
  const Chevron = expanded ? ChevronDownIcon : ChevronRightIcon;
  const isCompact = layout === 'compact';
  const isCatalogGrid = layout === 'catalog-grid';
  const isCatalogList = layout === 'catalog-list';

  const shellClass = `
    relative rounded-lg border text-left transition-colors overflow-hidden
    ${expanded
      ? isDark
        ? 'border-primary-500/40 bg-gray-800/80 shadow-md shadow-primary-500/5'
        : 'border-primary-500/30 bg-white shadow-md shadow-primary-500/5'
      : isDark
        ? 'border-gray-700 bg-gray-800/60 hover:border-primary-500/40 hover:bg-gray-800'
        : 'border-gray-200 bg-white hover:border-primary-500/40 hover:bg-gray-50'
    }
  `;

  const deleteButton = onDeleteAll && count > 0 && (
    <button
      type="button"
      onClick={(e) => {
        e.stopPropagation();
        onDeleteAll();
      }}
      title={deleteTitle}
      className={`absolute top-2 right-2 z-10 rounded-lg p-1.5 transition-colors ${
        isDark
          ? 'bg-gray-700/90 hover:bg-red-600 text-gray-400 hover:text-white'
          : 'bg-gray-100/90 hover:bg-red-500 text-gray-500 hover:text-white'
      }`}
    >
      <TrashIcon className="w-4 h-4" />
    </button>
  );

  const folderThumb = (size: 'sm' | 'lg') => (
    <div
      className={`relative flex items-center justify-center rounded-lg overflow-hidden ${
        isDark ? 'bg-primary-500/15' : 'bg-primary-500/10'
      } ${size === 'lg' ? 'aspect-square mb-3' : 'flex-1 min-h-0 mb-1'}`}
      style={
        isCompact && !expanded
          ? { height: cardWidth - 40 }
          : undefined
      }
    >
      <div
        className={`absolute inset-0 opacity-40 ${
          isDark ? 'bg-primary-500/20' : 'bg-primary-500/15'
        }`}
        style={{
          backgroundImage: `repeating-linear-gradient(
            -45deg,
            transparent,
            transparent 6px,
            ${isDark ? 'rgba(20,127,212,0.12)' : 'rgba(20,127,212,0.08)'} 6px,
            ${isDark ? 'rgba(20,127,212,0.12)' : 'rgba(20,127,212,0.08)'} 12px
          )`,
        }}
      />
      <FolderIcon
        className={`relative text-primary-500 ${
          size === 'lg' ? 'w-12 h-12' : 'w-8 h-8'
        }`}
      />
      {!expanded && (
        <span
          className={`absolute bottom-1.5 right-1.5 rounded-full px-1.5 py-0.5 text-[10px] font-semibold tabular-nums ${
            isDark ? 'bg-gray-900/80 text-primary-300' : 'bg-white/90 text-primary-600'
          }`}
        >
          {count}
        </span>
      )}
    </div>
  );

  const collapsedFace = (
    <button
      type="button"
      onClick={onToggle}
      className={`w-full h-full flex flex-col p-2 ${isCatalogList ? 'flex-row items-center gap-3 p-4' : ''}`}
      aria-expanded={expanded}
    >
      {isCatalogList ? (
        <>
          <div
            className={`flex-shrink-0 w-16 h-16 rounded-lg flex items-center justify-center ${
              isDark ? 'bg-primary-500/15' : 'bg-primary-500/10'
            }`}
          >
            <FolderIcon className="w-8 h-8 text-primary-500" />
          </div>
          <div className="flex-1 min-w-0 text-left">
            <div className={`font-medium text-sm truncate ${isDark ? 'text-white' : 'text-gray-900'}`}>
              {title}
            </div>
            <div className={`text-xs ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
              {count} imported unit asset{count === 1 ? '' : 's'}
            </div>
          </div>
          <Chevron className={`w-5 h-5 flex-shrink-0 ${isDark ? 'text-gray-400' : 'text-gray-500'}`} />
        </>
      ) : (
        <>
          {folderThumb(isCatalogGrid ? 'lg' : 'sm')}
          <div className="flex items-center justify-between gap-1 min-w-0">
            <span
              className={`text-xs font-medium truncate flex-1 ${
                isDark ? 'text-gray-200' : 'text-gray-800'
              }`}
            >
              {title}
            </span>
            <Chevron className={`w-3.5 h-3.5 flex-shrink-0 ${isDark ? 'text-gray-500' : 'text-gray-400'}`} />
          </div>
          {isCatalogGrid && (
            <p className={`text-xs truncate ${isDark ? 'text-gray-400' : 'text-gray-500'}`}>
              {count} asset{count === 1 ? '' : 's'} · click to open
            </p>
          )}
        </>
      )}
    </button>
  );

  const expandedHeader = (
    <div
      className={`flex items-center gap-2 px-3 py-2 border-b ${
        isDark ? 'border-gray-700/80 bg-gray-900/40' : 'border-gray-100 bg-gray-50/80'
      }`}
    >
      <button
        type="button"
        onClick={onToggle}
        className="flex items-center gap-2 flex-1 min-w-0 text-left"
        aria-expanded={expanded}
      >
        <Chevron className={`w-4 h-4 flex-shrink-0 ${isDark ? 'text-gray-400' : 'text-gray-500'}`} />
        <FolderIcon className="w-4 h-4 flex-shrink-0 text-primary-500" />
        <span className={`truncate font-medium text-sm ${isDark ? 'text-gray-100' : 'text-gray-800'}`}>
          {title}
        </span>
        <span
          className={`flex-shrink-0 rounded-full px-2 py-0.5 text-xs tabular-nums ${
            isDark ? 'bg-gray-700 text-gray-300' : 'bg-gray-200 text-gray-600'
          }`}
        >
          {count}
        </span>
      </button>
      {onDeleteAll && count > 0 && (
        <button
          type="button"
          onClick={onDeleteAll}
          title={deleteTitle}
          className={`flex-shrink-0 rounded-lg p-1.5 transition-colors ${
            isDark
              ? 'text-gray-400 hover:bg-red-600 hover:text-white'
              : 'text-gray-500 hover:bg-red-500 hover:text-white'
          }`}
        >
          <TrashIcon className="w-4 h-4" />
        </button>
      )}
    </div>
  );

  const innerGridStyle =
    isCompact && columns
      ? {
          display: 'grid' as const,
          gridTemplateColumns: `repeat(${columns}, ${cardWidth}px)`,
          gap: `${gap}px`,
        }
      : undefined;

  return (
    <motion.div
      layout
      transition={{ type: 'spring', stiffness: 420, damping: 34 }}
      className={`${shellClass} ${expanded && (isCatalogGrid || isCatalogList) ? 'col-span-full' : ''}`}
      style={{
        gridColumn: expanded ? '1 / -1' : undefined,
        width: isCompact && !expanded ? cardWidth : undefined,
        height: isCompact && !expanded ? cardHeight : undefined,
      }}
    >
      {!expanded && deleteButton}
      <AnimatePresence initial={false} mode="wait">
        {!expanded ? (
          <motion.div
            key="collapsed"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.15 }}
            className={isCatalogGrid ? 'p-4' : 'h-full'}
          >
            {collapsedFace}
          </motion.div>
        ) : (
          <motion.div
            key="expanded"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.18 }}
          >
            {expandedHeader}
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.22, ease: 'easeOut' }}
              className="overflow-hidden"
            >
              <div className={isCompact ? 'p-2' : 'p-3'}>
                <div
                  className={!isCompact ? innerGridClassName : undefined}
                  style={innerGridStyle}
                >
                  {children}
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
};
