import {
  isAutoGeneratedGatewayName,
  isOperatorSetGatewayDisplayName,
  resolveBoundGatewayDisplayName,
  unboundGatewayDisplayName,
  withOperatorSetGatewayDisplayName,
} from '@/utils/gateway-display-name.utils';

describe('gateway-display-name.utils', () => {
  it('detects auto-generated labels', () => {
    expect(isAutoGeneratedGatewayName('Gateway deadbeef', 'deadbeef-xxxx')).toBe(true);
    expect(isAutoGeneratedGatewayName('Swap candidate deadbeef')).toBe(true);
    expect(isAutoGeneratedGatewayName('Unbound gateway deadbeef')).toBe(true);
    expect(isAutoGeneratedGatewayName('Westside Storage')).toBe(false);
  });

  it('uses facility name unless operator set the display name', () => {
    expect(
      resolveBoundGatewayDisplayName({
        facilityName: 'North Depot',
        gatewayId: 'deadbeef-1111',
        existingName: 'Other Facility Gateway',
      }),
    ).toBe('North Depot');

    expect(
      resolveBoundGatewayDisplayName({
        facilityName: 'North Depot',
        gatewayId: 'deadbeef-1111',
        existingName: 'Front Gate Hub',
        metadata: { displayNameSetByOperator: true },
      }),
    ).toBe('Front Gate Hub');
  });

  it('marks and clears operator-set metadata', () => {
    expect(isOperatorSetGatewayDisplayName({ displayNameSetByOperator: true })).toBe(true);
    expect(withOperatorSetGatewayDisplayName({ autoRegistered: true }, true)).toEqual({
      autoRegistered: true,
      displayNameSetByOperator: true,
    });
    expect(withOperatorSetGatewayDisplayName({ displayNameSetByOperator: true }, false)).toEqual(
      {},
    );
    expect(unboundGatewayDisplayName('abcdef01-rest')).toBe('Unbound gateway abcdef01');
  });
});
