/** Metadata flag set when an operator renames a gateway via API/UI. */
export const GATEWAY_DISPLAY_NAME_OPERATOR_SET_KEY = 'displayNameSetByOperator';

function parseGatewayMetadata(metadata: unknown): Record<string, unknown> {
  if (!metadata) return {};
  if (typeof metadata === 'string') {
    try {
      const parsed = JSON.parse(metadata);
      return parsed && typeof parsed === 'object' && !Array.isArray(parsed)
        ? (parsed as Record<string, unknown>)
        : {};
    } catch {
      return {};
    }
  }
  if (typeof metadata === 'object' && !Array.isArray(metadata)) {
    return { ...(metadata as Record<string, unknown>) };
  }
  return {};
}

export function isOperatorSetGatewayDisplayName(metadata: unknown): boolean {
  return parseGatewayMetadata(metadata)[GATEWAY_DISPLAY_NAME_OPERATOR_SET_KEY] === true;
}

/** True for cloud auto-assigned labels (not an intentional operator rename). */
export function isAutoGeneratedGatewayName(name: unknown, gatewayId?: string): boolean {
  const n = String(name ?? '').trim();
  if (!n) return true;
  if (/^Gateway [0-9a-f]{8}$/i.test(n)) return true;
  if (/^Swap candidate [0-9a-f]{8}$/i.test(n)) return true;
  if (/^Unbound gateway [0-9a-f]{8}$/i.test(n)) return true;
  if (gatewayId) {
    const short = String(gatewayId).slice(0, 8);
    if (
      n === `Gateway ${short}` ||
      n === `Swap candidate ${short}` ||
      n === `Unbound gateway ${short}`
    ) {
      return true;
    }
  }
  return false;
}

/**
 * Display name for a gateway that is (or is becoming) bound to a facility.
 * Uses the facility name unless an operator has explicitly set the display name.
 */
export function resolveBoundGatewayDisplayName(params: {
  facilityName: string | null | undefined;
  gatewayId: string;
  existingName?: string | null;
  metadata?: unknown;
}): string {
  const existing = String(params.existingName ?? '').trim();
  if (isOperatorSetGatewayDisplayName(params.metadata) && existing) {
    return existing;
  }
  const facilityName = String(params.facilityName ?? '').trim();
  if (facilityName) {
    return facilityName;
  }
  return `Gateway ${String(params.gatewayId).slice(0, 8)}`;
}

export function unboundGatewayDisplayName(gatewayId: string): string {
  return `Unbound gateway ${String(gatewayId).slice(0, 8)}`;
}

export function withOperatorSetGatewayDisplayName(
  metadata: unknown,
  set: boolean,
): Record<string, unknown> {
  const next = parseGatewayMetadata(metadata);
  if (set) {
    next[GATEWAY_DISPLAY_NAME_OPERATOR_SET_KEY] = true;
  } else {
    delete next[GATEWAY_DISPLAY_NAME_OPERATOR_SET_KEY];
  }
  return next;
}
