/**
 * Build-in-3D Wizard — Asset generation (pure)
 *
 * Turns reviewed 2D units into a small set of reusable primitive storage-unit
 * asset definitions. Units with near-identical real dimensions and door layout
 * collapse into one shared asset (keyed by a rounded "signature") so a facility
 * with hundreds of units only needs a handful of assets.
 *
 * Door mapping (2D local frame -> 3D LockerSpec):
 *   2D width  (local x) -> 3D width  (X)
 *   2D height (local y) -> 3D depth  (Z)
 *   side: top->back, bottom->front, left->left, right->right
 *   offsetFraction -> doorPositionX (meters; for left/right this is the Z axis)
 */

import { feetToMeters, metersToFeet, metersToGridUnits } from '../../core/types';
import { doorEdgeLength } from '../geometry';
import {
  AUTO_ASSET_SIGNATURE_PREFIX,
  autoAssetSignature,
} from '../../assets/autoGenerated';
import type { CreateAssetDefinitionInput, LockerSpec } from '../../services/AssetService';
import type { DoorSide, EditableUnit } from '../types';

/** Default storage-unit height when the plan only gives a 2D footprint. */
export const DEFAULT_UNIT_HEIGHT_M = feetToMeters(8);

/** White header band above the roll-up door (unit-number plaque zone). */
export const DEFAULT_DOOR_HEADER_RATIO = 0.1;

/** Small sill clearance — door sits slightly above the gravel line. */
export const DEFAULT_DOOR_BASE_OFFSET_M = feetToMeters(0.15);

/** Door height + vertical placement tuned to match typical outdoor roll-up units. */
export function defaultDoorDimensions(heightM: number = DEFAULT_UNIT_HEIGHT_M): {
  doorHeight: number;
  doorPositionY: number;
} {
  const baseY = Math.min(DEFAULT_DOOR_BASE_OFFSET_M, heightM * 0.04);
  const headerBand = heightM * DEFAULT_DOOR_HEADER_RATIO;
  const doorHeight = Math.max(feetToMeters(2), heightM - headerBand - baseY);
  return { doorHeight, doorPositionY: baseY };
}

/** Default reuse tolerance: units within ~0.5 ft on each axis share an asset. */
export const DEFAULT_TOLERANCE_M = feetToMeters(0.5);

const SIGNATURE_PREFIX = AUTO_ASSET_SIGNATURE_PREFIX;

/** Map a 2D door side to the 3D locker door side. */
export function doorSideToLockerSide(side: DoorSide): LockerSpec['doorSide'] {
  switch (side) {
    case 'top':
      return 'back';
    case 'bottom':
      return 'front';
    case 'left':
      return 'left';
    case 'right':
      return 'right';
  }
}

export interface UnitRealSpec {
  /** 3D width (X) in meters. */
  width: number;
  /** 3D depth (Z) in meters. */
  depth: number;
  /** Height in meters. */
  height: number;
  lockerSpec: LockerSpec;
}

/** Compute a single unit's real-world dimensions + door spec from the scale. */
export function unitRealSpec(
  unit: EditableUnit,
  metersPerPixel: number,
  heightM: number = DEFAULT_UNIT_HEIGHT_M
): UnitRealSpec {
  const width = unit.bounds.width * metersPerPixel;
  const depth = unit.bounds.height * metersPerPixel;
  const { doorHeight, doorPositionY } = defaultDoorDimensions(heightM);

  let lockerSpec: LockerSpec;
  if (unit.door) {
    const edgeLenPx = doorEdgeLength(unit.bounds, unit.door.side);
    lockerSpec = {
      doorSide: doorSideToLockerSide(unit.door.side),
      doorWidth: Math.max(feetToMeters(1), unit.door.widthFraction * edgeLenPx * metersPerPixel),
      doorHeight,
      doorPositionX: unit.door.offsetFraction * edgeLenPx * metersPerPixel,
      doorPositionY,
    };
  } else {
    // No door assigned: default to a centered front door, 80% of the width.
    lockerSpec = {
      doorSide: 'front',
      doorWidth: Math.max(feetToMeters(1), 0.8 * width),
      doorHeight,
      doorPositionX: 0,
      doorPositionY,
    };
  }

  return { width, depth, height: heightM, lockerSpec };
}

function snap(value: number, tol: number): number {
  if (!(tol > 0)) return value;
  return Math.round(value / tol) * tol;
}

export interface AssetBucket {
  /** Stable signature embedded in the asset description for idempotent re-runs. */
  signature: string;
  name: string;
  dimensions: { width: number; height: number; depth: number };
  lockerSpec: LockerSpec;
  /** Diagram unit ids assigned to this bucket. */
  unitIds: string[];
}

export interface BucketOptions {
  toleranceM?: number;
  heightM?: number;
}

function capitalize(s: string): string {
  return s.length ? s[0].toUpperCase() + s.slice(1) : s;
}

function bucketName(widthM: number, depthM: number, side: LockerSpec['doorSide'], offsetM: number): string {
  let name = `Auto ${Math.round(metersToFeet(widthM))}\u00d7${Math.round(metersToFeet(depthM))} ft`;
  if (side !== 'front') name += ` \u00b7 ${capitalize(side)}`;
  if (Math.abs(offsetM) > 1e-4) name += ' \u00b7 offset';
  return name;
}

/**
 * Group units into reusable asset buckets. Each bucket's dimensions and door
 * spec are the rounded (snapped) representative values shared by every unit in it.
 */
export function bucketUnits(
  units: EditableUnit[],
  metersPerPixel: number,
  options: BucketOptions = {}
): AssetBucket[] {
  const tol = options.toleranceM ?? DEFAULT_TOLERANCE_M;
  const heightM = options.heightM ?? DEFAULT_UNIT_HEIGHT_M;
  const byKey = new Map<string, AssetBucket>();

  for (const unit of units) {
    const spec = unitRealSpec(unit, metersPerPixel, heightM);
    const sw = snap(spec.width, tol);
    const sd = snap(spec.depth, tol);
    const sh = snap(spec.height, tol);
    const sdw = snap(spec.lockerSpec.doorWidth, tol);
    const sdh = snap(spec.lockerSpec.doorHeight, tol);
    const soff = snap(spec.lockerSpec.doorPositionX, tol);
    const side = spec.lockerSpec.doorSide;
    const signature =
      `${SIGNATURE_PREFIX}:${sw.toFixed(3)}x${sh.toFixed(3)}x${sd.toFixed(3)}` +
      `|${side}|w${sdw.toFixed(3)}|h${sdh.toFixed(3)}|o${soff.toFixed(3)}`;

    let bucket = byKey.get(signature);
    if (!bucket) {
      bucket = {
        signature,
        name: bucketName(sw, sd, side, soff),
        dimensions: { width: sw, height: sh, depth: sd },
        lockerSpec: {
          doorSide: side,
          doorWidth: sdw,
          doorHeight: sdh,
          doorPositionX: soff,
          doorPositionY: 0,
        },
        unitIds: [],
      };
      byKey.set(signature, bucket);
    }
    bucket.unitIds.push(unit.id);
  }

  return [...byKey.values()];
}

/** Build the create-asset payload for a bucket (primitive storage unit). */
export function bucketToAssetInput(bucket: AssetBucket): CreateAssetDefinitionInput {
  return {
    name: bucket.name,
    description: `[${bucket.signature}] Auto-generated from layout import`,
    category: 'storage_unit',
    modelType: 'primitive',
    dimensions: bucket.dimensions,
    gridUnits: {
      x: Math.max(1, metersToGridUnits(bucket.dimensions.width)),
      z: Math.max(1, metersToGridUnits(bucket.dimensions.depth)),
    },
    isSmart: true,
    canRotate: true,
    canStack: false,
    lockerSpec: bucket.lockerSpec,
  };
}

/** Extract an auto-layout signature from an existing asset description, if any. */
export function signatureOf(description?: string): string | null {
  return autoAssetSignature(description);
}

export interface MatchableAssetDefinition {
  id: string;
  category: string;
  modelType?: string;
  dimensions: { width: number; height: number; depth: number };
  lockerSpec?: LockerSpec;
  description?: string;
}

export type AssetMatchKind = 'signature' | 'fuzzy-signature' | 'dimensions' | 'footprint';

export interface ParsedLayoutSignature {
  width: number;
  height: number;
  depth: number;
  doorSide: LockerSpec['doorSide'];
  doorWidth: number;
  doorHeight: number;
  doorOffset: number;
}

const LAYOUT_SIGNATURE_RE =
  /^autolayout:([\d.]+)x([\d.]+)x([\d.]+)\|(front|back|left|right)\|w([\d.]+)\|h([\d.]+)\|o([\d.]+)$/;

function normalizeNumber(value: unknown, fallback = 0): number {
  const n = typeof value === 'number' ? value : Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function normalizeDimensions(dim: { width: number; height: number; depth: number }) {
  return {
    width: normalizeNumber(dim.width),
    height: normalizeNumber(dim.height),
    depth: normalizeNumber(dim.depth),
  };
}

function normalizeLockerSpec(spec: LockerSpec): LockerSpec {
  return {
    doorSide: spec.doorSide,
    doorWidth: normalizeNumber(spec.doorWidth),
    doorHeight: normalizeNumber(spec.doorHeight),
    doorPositionX: normalizeNumber(spec.doorPositionX),
    doorPositionY: normalizeNumber(spec.doorPositionY),
  };
}

/** Parse the canonical autolayout signature string into comparable components. */
export function parseAutoLayoutSignature(signature: string): ParsedLayoutSignature | null {
  const match = signature.match(LAYOUT_SIGNATURE_RE);
  if (!match) return null;
  return {
    width: normalizeNumber(match[1]),
    height: normalizeNumber(match[2]),
    depth: normalizeNumber(match[3]),
    doorSide: match[4] as LockerSpec['doorSide'],
    doorWidth: normalizeNumber(match[5]),
    doorHeight: normalizeNumber(match[6]),
    doorOffset: normalizeNumber(match[7]),
  };
}

export function lockerSpecFromParsed(parsed: ParsedLayoutSignature): LockerSpec {
  return {
    doorSide: parsed.doorSide,
    doorWidth: parsed.doorWidth,
    doorHeight: parsed.doorHeight,
    doorPositionX: parsed.doorOffset,
    doorPositionY: 0,
  };
}

export function layoutSignaturesMatch(
  a: ParsedLayoutSignature,
  b: ParsedLayoutSignature,
  toleranceM: number
): boolean {
  return (
    a.doorSide === b.doorSide &&
    nearEqual(a.width, b.width, toleranceM) &&
    nearEqual(a.height, b.height, toleranceM) &&
    nearEqual(a.depth, b.depth, toleranceM) &&
    nearEqual(a.doorWidth, b.doorWidth, toleranceM) &&
    nearEqual(a.doorHeight, b.doorHeight, toleranceM) &&
    nearEqual(a.doorOffset, b.doorOffset, toleranceM)
  );
}

function nearEqual(a: number, b: number, tol: number): boolean {
  return Math.abs(a - b) <= tol;
}

export function dimensionsMatch(
  a: { width: number; height: number; depth: number },
  b: { width: number; height: number; depth: number },
  toleranceM: number
): boolean {
  const left = normalizeDimensions(a);
  const right = normalizeDimensions(b);
  return (
    nearEqual(left.width, right.width, toleranceM) &&
    nearEqual(left.height, right.height, toleranceM) &&
    nearEqual(left.depth, right.depth, toleranceM)
  );
}

function lockerSpecsMatch(a: LockerSpec, b: LockerSpec, toleranceM: number): boolean {
  const left = normalizeLockerSpec(a);
  const right = normalizeLockerSpec(b);
  return (
    left.doorSide === right.doorSide &&
    nearEqual(left.doorWidth, right.doorWidth, toleranceM) &&
    nearEqual(left.doorHeight, right.doorHeight, toleranceM) &&
    nearEqual(left.doorPositionX, right.doorPositionX, toleranceM) &&
    nearEqual(left.doorPositionY, right.doorPositionY, toleranceM)
  );
}

function effectiveLockerSpec(def: MatchableAssetDefinition): LockerSpec | null {
  if (def.lockerSpec) {
    return normalizeLockerSpec(def.lockerSpec);
  }
  const sig = signatureOf(def.description);
  if (!sig) return null;
  const parsed = parseAutoLayoutSignature(sig);
  if (!parsed) return null;
  return lockerSpecFromParsed(parsed);
}

function isMatchableStorageUnit(def: MatchableAssetDefinition): boolean {
  if (def.category !== 'storage_unit') return false;
  if (def.modelType && def.modelType !== 'primitive') return false;
  return effectiveLockerSpec(def) !== null;
}

function footprintFeetMatch(
  bucket: AssetBucket,
  def: MatchableAssetDefinition,
  toleranceM: number
): boolean {
  const bucketLocker = normalizeLockerSpec(bucket.lockerSpec);
  const defLocker = effectiveLockerSpec(def);
  if (!defLocker) return false;
  if (bucketLocker.doorSide !== defLocker.doorSide) return false;

  const bucketWFt = Math.round(metersToFeet(bucket.dimensions.width));
  const bucketDFt = Math.round(metersToFeet(bucket.dimensions.depth));
  const defWFt = Math.round(metersToFeet(normalizeNumber(def.dimensions.width)));
  const defDFt = Math.round(metersToFeet(normalizeNumber(def.dimensions.depth)));
  if (bucketWFt !== defWFt || bucketDFt !== defDFt) return false;

  return lockerSpecsMatch(bucketLocker, defLocker, Math.max(toleranceM, feetToMeters(0.75)));
}

function findAssetIdByFuzzySignature(
  bucket: AssetBucket,
  existing: MatchableAssetDefinition[],
  toleranceM: number
): string | null {
  const target = parseAutoLayoutSignature(bucket.signature);
  if (!target) return null;

  for (const def of existing) {
    const sig = signatureOf(def.description);
    if (!sig) continue;
    const parsed = parseAutoLayoutSignature(sig);
    if (!parsed) continue;
    if (layoutSignaturesMatch(target, parsed, toleranceM)) {
      return def.id;
    }
  }

  return null;
}

/**
 * Find an existing primitive storage-unit asset with matching dimensions and door layout.
 * Used when auto-generating import assets so manually created units are reused.
 */
export function findMatchingAssetForBucket(
  bucket: AssetBucket,
  existing: MatchableAssetDefinition[],
  toleranceM: number = DEFAULT_TOLERANCE_M
): string | null {
  for (const def of existing) {
    if (!isMatchableStorageUnit(def)) continue;
    const locker = effectiveLockerSpec(def);
    if (!locker) continue;
    if (!dimensionsMatch(bucket.dimensions, def.dimensions, toleranceM)) continue;
    if (!lockerSpecsMatch(bucket.lockerSpec, locker, toleranceM)) continue;
    return def.id;
  }
  return null;
}

function findMatchingAssetByFootprint(
  bucket: AssetBucket,
  existing: MatchableAssetDefinition[],
  toleranceM: number
): string | null {
  for (const def of existing) {
    if (!isMatchableStorageUnit(def)) continue;
    if (!footprintFeetMatch(bucket, def, toleranceM)) continue;
    return def.id;
  }
  return null;
}

export interface AssetBucketResolution {
  assetId: string;
  matchKind: AssetMatchKind;
}

export interface ResolvedAssetBucket extends AssetBucket {
  assetId: string;
  matchKind: AssetMatchKind | 'created';
}

/** Resolve an asset id for a bucket: exact signature, fuzzy signature, dimensions, footprint. */
export function resolveAssetIdForBucket(
  bucket: AssetBucket,
  signatureIndex: Map<string, string>,
  existing: MatchableAssetDefinition[],
  toleranceM: number = DEFAULT_TOLERANCE_M
): AssetBucketResolution | null {
  const exactId = signatureIndex.get(bucket.signature);
  if (exactId) {
    return { assetId: exactId, matchKind: 'signature' };
  }

  const fuzzyId = findAssetIdByFuzzySignature(bucket, existing, toleranceM);
  if (fuzzyId) {
    return { assetId: fuzzyId, matchKind: 'fuzzy-signature' };
  }

  const dimensionId = findMatchingAssetForBucket(bucket, existing, toleranceM);
  if (dimensionId) {
    return { assetId: dimensionId, matchKind: 'dimensions' };
  }

  const footprintId = findMatchingAssetByFootprint(bucket, existing, toleranceM);
  if (footprintId) {
    return { assetId: footprintId, matchKind: 'footprint' };
  }

  return null;
}
